service: nodeless

provider:
  name: aws
  runtime: nodejs10.x
  region: sa-east-1 #São Paulo
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow #quais servicos da aws esta autorizado a acessar
      Action:
        - s3:GetObject #buscar arquivos no s3
        - s3:PutObject #salvar arquivos no s3
      Resource:
        - "arn:aws:s3:::*"

functions:
  optimize:
    handler: optimize.handle
    environment:
      bucket: charlesmendes-serverless #nome do bucket que iremos utilizar
    events:
      - s3:
          bucket: charlesmendes-serverless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/ #dispara apenas para arquivos de imagem
            - suffix: .jpg
      - s3:
          bucket: charlesmendes-serverless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/ #dispara apenas para arquivos de imagem
            - suffix: .png
